CREATE TABLE public.resultado (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	candidato varchar(255) NOT NULL,
	votos int4 NOT NULL,
	CONSTRAINT resultado_pkey PRIMARY KEY (id)
);

CREATE TABLE public.urna (
	id bigserial NOT NULL,
	codigo_identificacao varchar(255) NOT NULL,
	municipio varchar(255) NOT NULL,
	zona_eleitoral varchar(255) NOT NULL,
	secao_eleitoral varchar(255) NOT NULL,
	votos_validos int4 NOT NULL,
	votos_brancos int4 NOT NULL,
	votos_nulos int4 NOT NULL,
	CONSTRAINT urna_codigo_identificacao_key UNIQUE (codigo_identificacao),
	CONSTRAINT urna_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cargo (
	id bigserial NOT NULL,
	descricao varchar(255) NOT NULL,
	CONSTRAINT cargo_pkey PRIMARY KEY (id)
);

CREATE TABLE public.candidato (
	id bigserial NOT NULL,
	urna_id int8 NULL,
	cargo_id int8 NULL,
	nome varchar(255) NOT NULL,
	partido varchar(255) NOT NULL,
	numero int4 NOT NULL,
	votos int4 NOT NULL,
	CONSTRAINT candidato_pkey PRIMARY KEY (id),
	CONSTRAINT candidato_cargo_id_fkey FOREIGN KEY (cargo_id) REFERENCES public.cargo(id),
	CONSTRAINT candidato_urna_id_fkey FOREIGN KEY (urna_id) REFERENCES public.urna(id) ON DELETE CASCADE
);